name: Benchmark with version
# Run on push only for master, if not it will trigger push & pull_request on PRs at the same time
on:
  push:
    paths-ignore:
      # Any update here needs to be done for
      # - `pull_request` see below
      # - https://github.com/prisma/prisma/blob/master/src/.buildkite/test/buildkite-entry.sh
      # - https://github.com/prisma/prisma/blob/master/src/.buildkite/publish/buildkite-entry.sh
      - "*.md"
      - ".vscode/**"
      - "docs/**"
      - "examples/**"
      - "LICENSE"
      - "src/.buildkite/**"
      - "src/.dockerignore"
      - "src/scripts/ci/publish.ts"
      - "src/graphs/**"

env:
  PRISMA_TELEMETRY_INFORMATION: "prisma benchmark.yml"

jobs:
  benchmark:
    name: all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - run: yarn global add prisma@2.21.0
      - run: npm i --silent -g pnpm@5.15.1 --unsafe-perm
      - run: pnpm install

      - name: Run benchmarks
        run: yarn ts-node scripts/bench.ts | tee output.txt

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark
          tool: "benchmarkjs"
          output-file-path: output.txt
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@williamluke4"
          benchmark-data-dir-path: "janpio/pr" # TODO
